// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXmrB5Yx3sjLneigTMje_kBLBx4jkKlvg',
    appId: '1:380078754041:android:d98f47f3746fd873df3a28',
    messagingSenderId: '380078754041',
    projectId: 'quiz-app-d1f94',
    storageBucket: 'quiz-app-d1f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItQsWeRkRO3Cs7j3kdAHo4_FWxIl8E4U',
    appId: '1:380078754041:ios:e682fcd6babd4f4ddf3a28',
    messagingSenderId: '380078754041',
    projectId: 'quiz-app-d1f94',
    storageBucket: 'quiz-app-d1f94.appspot.com',
    androidClientId: '380078754041-jte5ohf2nskvk5rgaels3lojbsibcluc.apps.googleusercontent.com',
    iosClientId: '380078754041-4k0op13rgt7uceje56do54vinrj1lg79.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAi',
  );
}
